apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_DB: taskapp
  POSTGRES_USER: taskapp_user
  POSTGRES_PASSWORD: TaskApp@Secure2024!
  DATABASE_URL: postgresql://taskapp_user:TaskApp@Secure2024!@postgres-service:5432/taskapp
